apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira
  namespace: atlassian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: jira
        image: repository.rahyab.ir/jiracracked:latest
        ports:
        - containerPort: 8080
        env:
        - name: ATL_DB_TYPE
          value: postgres72
        - name: ATL_JDBC_URL
          value: jdbc:postgresql://jira-postgresql/jiradb
        - name: ATL_JDBC_USER
          value: jirauser
        - name: ATL_JDBC_PASSWORD
          value: DBPassword
        - name: JVM_SUPPORT_RECOMMENDED_ARGS
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "10Gi"
            cpu: "4"
        volumeMounts:
        - mountPath: "/var/atlassian/application-data/jira"
          name: jira-home
        - mountPath: /opt/atlassian/jira/conf/server.xml
          subPath: server.xml
          name: jira-config
        - mountPath: /opt/atlassian/jira/bin/setenv.sh
          subPath: setenv.sh
          name: jira-setenv
      volumes:
      - name: jira-home
        persistentVolumeClaim:
          claimName: jira-home
      - name: jira-config
        configMap:
          name: jira-server-xml
      - name: jira-setenv
        configMap:
          name: jira-setenv

